{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 75,
   "metadata": {},
   "outputs": [],
   "source": [
    "%reload_ext lab_black\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from plotnine import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [],
   "source": [
    "# read data\n",
    "od = pd.read_csv(\n",
    "    \"https://raw.githubusercontent.com/MIDS-at-Duke/estimating-impact-of-opioids-2020-purlple-team/coneel/10_code/od_deaths_state.csv?token=ARFW6V3OWJEBEXR6EAMOD4S7SS5MM\"\n",
    ")\n",
    "\n",
    "population = pd.read_csv(\n",
    "    \"https://raw.githubusercontent.com/MIDS-at-Duke/estimating-impact-of-opioids-2020-purlple-team/ssloate/20_intermediate_files/countypopulations_clean.csv?token=ARFW6VZYS6HL4RX22US75US7S52K6\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "metadata": {},
   "outputs": [],
   "source": [
    "# rename od columns to match\n",
    "od = od.rename(columns={\"County Code\": \"FIPS\"})\n",
    "\n",
    "# drop _merge column in popualtion dataset\n",
    "population = population.drop(columns=\"_merge\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [],
   "source": [
    "# remove Alaska from od Data\n",
    "od = od[od[\"State\"] != \"AK\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 117,
   "metadata": {},
   "outputs": [],
   "source": [
    "# merge dataset. Use right merge, because it's okay if some years/counties don't have data in the od dataset. That just means there were less than 10 deaths\n",
    "od_pop = pd.merge(population, od, on=[\"FIPS\", \"Year\"], how=\"right\", indicator=True)\n",
    "\n",
    "assert od_pop[od_pop[\"_merge\"] == \"both\"].all"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>State Name</th>\n",
       "      <th>County_x</th>\n",
       "      <th>Year</th>\n",
       "      <th>Population</th>\n",
       "      <th>FIPS</th>\n",
       "      <th>State Abbr</th>\n",
       "      <th>County_y</th>\n",
       "      <th>State</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>_merge</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>6906</th>\n",
       "      <td>37072.0</td>\n",
       "      <td>New York</td>\n",
       "      <td>Suffolk County</td>\n",
       "      <td>2012</td>\n",
       "      <td>1496982.0</td>\n",
       "      <td>36103</td>\n",
       "      <td>NY</td>\n",
       "      <td>Suffolk County</td>\n",
       "      <td>NY</td>\n",
       "      <td>287.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>656</th>\n",
       "      <td>50348.0</td>\n",
       "      <td>Texas</td>\n",
       "      <td>Brazos County</td>\n",
       "      <td>2008</td>\n",
       "      <td>185098.0</td>\n",
       "      <td>48041</td>\n",
       "      <td>TX</td>\n",
       "      <td>Brazos County</td>\n",
       "      <td>TX</td>\n",
       "      <td>10.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>650</th>\n",
       "      <td>50330.0</td>\n",
       "      <td>Texas</td>\n",
       "      <td>Brazoria County</td>\n",
       "      <td>2010</td>\n",
       "      <td>314428.0</td>\n",
       "      <td>48039</td>\n",
       "      <td>TX</td>\n",
       "      <td>Brazoria County</td>\n",
       "      <td>TX</td>\n",
       "      <td>24.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6811</th>\n",
       "      <td>22766.0</td>\n",
       "      <td>Louisiana</td>\n",
       "      <td>St. Tammany Parish</td>\n",
       "      <td>2006</td>\n",
       "      <td>223133.0</td>\n",
       "      <td>22103</td>\n",
       "      <td>LA</td>\n",
       "      <td>St. Tammany Parish</td>\n",
       "      <td>LA</td>\n",
       "      <td>64.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>589</th>\n",
       "      <td>29327.0</td>\n",
       "      <td>Missouri</td>\n",
       "      <td>Boone County</td>\n",
       "      <td>2007</td>\n",
       "      <td>155666.0</td>\n",
       "      <td>29019</td>\n",
       "      <td>MO</td>\n",
       "      <td>Boone County</td>\n",
       "      <td>MO</td>\n",
       "      <td>15.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>457</th>\n",
       "      <td>59372.0</td>\n",
       "      <td>West Virginia</td>\n",
       "      <td>Berkeley County</td>\n",
       "      <td>2012</td>\n",
       "      <td>106965.0</td>\n",
       "      <td>54003</td>\n",
       "      <td>WV</td>\n",
       "      <td>Berkeley County</td>\n",
       "      <td>WV</td>\n",
       "      <td>27.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1378</th>\n",
       "      <td>40572.0</td>\n",
       "      <td>Ohio</td>\n",
       "      <td>Clark County</td>\n",
       "      <td>2012</td>\n",
       "      <td>137171.0</td>\n",
       "      <td>39023</td>\n",
       "      <td>OH</td>\n",
       "      <td>Clark County</td>\n",
       "      <td>OH</td>\n",
       "      <td>36.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5804</th>\n",
       "      <td>60131.0</td>\n",
       "      <td>West Virginia</td>\n",
       "      <td>Putnam County</td>\n",
       "      <td>2011</td>\n",
       "      <td>56030.0</td>\n",
       "      <td>54079</td>\n",
       "      <td>WV</td>\n",
       "      <td>Putnam County</td>\n",
       "      <td>WV</td>\n",
       "      <td>12.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7182</th>\n",
       "      <td>37152.0</td>\n",
       "      <td>New York</td>\n",
       "      <td>Ulster County</td>\n",
       "      <td>2012</td>\n",
       "      <td>181538.0</td>\n",
       "      <td>36111</td>\n",
       "      <td>NY</td>\n",
       "      <td>Ulster County</td>\n",
       "      <td>NY</td>\n",
       "      <td>12.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2058</th>\n",
       "      <td>33114.0</td>\n",
       "      <td>Nebraska</td>\n",
       "      <td>Douglas County</td>\n",
       "      <td>2014</td>\n",
       "      <td>543005.0</td>\n",
       "      <td>31055</td>\n",
       "      <td>NE</td>\n",
       "      <td>Douglas County</td>\n",
       "      <td>NE</td>\n",
       "      <td>48.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4713</th>\n",
       "      <td>35213.0</td>\n",
       "      <td>New Jersey</td>\n",
       "      <td>Monmouth County</td>\n",
       "      <td>2013</td>\n",
       "      <td>626912.0</td>\n",
       "      <td>34025</td>\n",
       "      <td>NJ</td>\n",
       "      <td>Monmouth County</td>\n",
       "      <td>NJ</td>\n",
       "      <td>72.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7116</th>\n",
       "      <td>10035.0</td>\n",
       "      <td>Georgia</td>\n",
       "      <td>Troup County</td>\n",
       "      <td>2015</td>\n",
       "      <td>69595.0</td>\n",
       "      <td>13285</td>\n",
       "      <td>GA</td>\n",
       "      <td>Troup County</td>\n",
       "      <td>GA</td>\n",
       "      <td>10.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7778</th>\n",
       "      <td>61855.0</td>\n",
       "      <td>Wisconsin</td>\n",
       "      <td>Winnebago County</td>\n",
       "      <td>2015</td>\n",
       "      <td>169246.0</td>\n",
       "      <td>55139</td>\n",
       "      <td>WI</td>\n",
       "      <td>Winnebago County</td>\n",
       "      <td>WI</td>\n",
       "      <td>22.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7172</th>\n",
       "      <td>1251.0</td>\n",
       "      <td>Alabama</td>\n",
       "      <td>Tuscaloosa County</td>\n",
       "      <td>2011</td>\n",
       "      <td>196745.0</td>\n",
       "      <td>1125</td>\n",
       "      <td>AL</td>\n",
       "      <td>Tuscaloosa County</td>\n",
       "      <td>AL</td>\n",
       "      <td>21.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>224</th>\n",
       "      <td>21791.0</td>\n",
       "      <td>Louisiana</td>\n",
       "      <td>Ascension Parish</td>\n",
       "      <td>2011</td>\n",
       "      <td>110075.0</td>\n",
       "      <td>22005</td>\n",
       "      <td>LA</td>\n",
       "      <td>Ascension Parish</td>\n",
       "      <td>LA</td>\n",
       "      <td>11.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6834</th>\n",
       "      <td>4132.0</td>\n",
       "      <td>California</td>\n",
       "      <td>Stanislaus County</td>\n",
       "      <td>2012</td>\n",
       "      <td>520424.0</td>\n",
       "      <td>6099</td>\n",
       "      <td>CA</td>\n",
       "      <td>Stanislaus County</td>\n",
       "      <td>CA</td>\n",
       "      <td>66.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5626</th>\n",
       "      <td>24048.0</td>\n",
       "      <td>Massachusetts</td>\n",
       "      <td>Plymouth County</td>\n",
       "      <td>2008</td>\n",
       "      <td>490371.0</td>\n",
       "      <td>25023</td>\n",
       "      <td>MA</td>\n",
       "      <td>Plymouth County</td>\n",
       "      <td>MA</td>\n",
       "      <td>49.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6063</th>\n",
       "      <td>34915.0</td>\n",
       "      <td>New Hampshire</td>\n",
       "      <td>Rockingham County</td>\n",
       "      <td>2015</td>\n",
       "      <td>302691.0</td>\n",
       "      <td>33015</td>\n",
       "      <td>NH</td>\n",
       "      <td>Rockingham County</td>\n",
       "      <td>NH</td>\n",
       "      <td>85.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1785</th>\n",
       "      <td>40715.0</td>\n",
       "      <td>Ohio</td>\n",
       "      <td>Darke County</td>\n",
       "      <td>2015</td>\n",
       "      <td>51981.0</td>\n",
       "      <td>39037</td>\n",
       "      <td>OH</td>\n",
       "      <td>Darke County</td>\n",
       "      <td>OH</td>\n",
       "      <td>13.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7832</th>\n",
       "      <td>60430.0</td>\n",
       "      <td>West Virginia</td>\n",
       "      <td>Wyoming County</td>\n",
       "      <td>2010</td>\n",
       "      <td>23728.0</td>\n",
       "      <td>54109</td>\n",
       "      <td>WV</td>\n",
       "      <td>Wyoming County</td>\n",
       "      <td>WV</td>\n",
       "      <td>24.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1593</th>\n",
       "      <td>3266.0</td>\n",
       "      <td>California</td>\n",
       "      <td>Contra Costa County</td>\n",
       "      <td>2006</td>\n",
       "      <td>1000834.0</td>\n",
       "      <td>6013</td>\n",
       "      <td>CA</td>\n",
       "      <td>Contra Costa County</td>\n",
       "      <td>CA</td>\n",
       "      <td>74.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2505</th>\n",
       "      <td>62015.0</td>\n",
       "      <td>Wyoming</td>\n",
       "      <td>Fremont County</td>\n",
       "      <td>2015</td>\n",
       "      <td>40219.0</td>\n",
       "      <td>56013</td>\n",
       "      <td>WY</td>\n",
       "      <td>Fremont County</td>\n",
       "      <td>WY</td>\n",
       "      <td>10.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4717</th>\n",
       "      <td>59954.0</td>\n",
       "      <td>West Virginia</td>\n",
       "      <td>Monongalia County</td>\n",
       "      <td>2014</td>\n",
       "      <td>103480.0</td>\n",
       "      <td>54061</td>\n",
       "      <td>WV</td>\n",
       "      <td>Monongalia County</td>\n",
       "      <td>WV</td>\n",
       "      <td>13.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4411</th>\n",
       "      <td>10468.0</td>\n",
       "      <td>Hawaii</td>\n",
       "      <td>Maui County</td>\n",
       "      <td>2014</td>\n",
       "      <td>89.0</td>\n",
       "      <td>15009</td>\n",
       "      <td>HI</td>\n",
       "      <td>Maui County</td>\n",
       "      <td>HI</td>\n",
       "      <td>18.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1048</th>\n",
       "      <td>7652.0</td>\n",
       "      <td>Georgia</td>\n",
       "      <td>Carroll County</td>\n",
       "      <td>2012</td>\n",
       "      <td>111412.0</td>\n",
       "      <td>13045</td>\n",
       "      <td>GA</td>\n",
       "      <td>Carroll County</td>\n",
       "      <td>GA</td>\n",
       "      <td>13.0</td>\n",
       "      <td>both</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      Unnamed: 0     State Name             County_x  Year  Population   FIPS  \\\n",
       "6906     37072.0       New York       Suffolk County  2012   1496982.0  36103   \n",
       "656      50348.0          Texas        Brazos County  2008    185098.0  48041   \n",
       "650      50330.0          Texas      Brazoria County  2010    314428.0  48039   \n",
       "6811     22766.0      Louisiana   St. Tammany Parish  2006    223133.0  22103   \n",
       "589      29327.0       Missouri         Boone County  2007    155666.0  29019   \n",
       "457      59372.0  West Virginia      Berkeley County  2012    106965.0  54003   \n",
       "1378     40572.0           Ohio         Clark County  2012    137171.0  39023   \n",
       "5804     60131.0  West Virginia        Putnam County  2011     56030.0  54079   \n",
       "7182     37152.0       New York        Ulster County  2012    181538.0  36111   \n",
       "2058     33114.0       Nebraska       Douglas County  2014    543005.0  31055   \n",
       "4713     35213.0     New Jersey      Monmouth County  2013    626912.0  34025   \n",
       "7116     10035.0        Georgia         Troup County  2015     69595.0  13285   \n",
       "7778     61855.0      Wisconsin     Winnebago County  2015    169246.0  55139   \n",
       "7172      1251.0        Alabama    Tuscaloosa County  2011    196745.0   1125   \n",
       "224      21791.0      Louisiana     Ascension Parish  2011    110075.0  22005   \n",
       "6834      4132.0     California    Stanislaus County  2012    520424.0   6099   \n",
       "5626     24048.0  Massachusetts      Plymouth County  2008    490371.0  25023   \n",
       "6063     34915.0  New Hampshire    Rockingham County  2015    302691.0  33015   \n",
       "1785     40715.0           Ohio         Darke County  2015     51981.0  39037   \n",
       "7832     60430.0  West Virginia       Wyoming County  2010     23728.0  54109   \n",
       "1593      3266.0     California  Contra Costa County  2006   1000834.0   6013   \n",
       "2505     62015.0        Wyoming       Fremont County  2015     40219.0  56013   \n",
       "4717     59954.0  West Virginia    Monongalia County  2014    103480.0  54061   \n",
       "4411     10468.0         Hawaii          Maui County  2014        89.0  15009   \n",
       "1048      7652.0        Georgia       Carroll County  2012    111412.0  13045   \n",
       "\n",
       "     State Abbr             County_y State  Deaths _merge  \n",
       "6906         NY       Suffolk County    NY   287.0   both  \n",
       "656          TX        Brazos County    TX    10.0   both  \n",
       "650          TX      Brazoria County    TX    24.0   both  \n",
       "6811         LA   St. Tammany Parish    LA    64.0   both  \n",
       "589          MO         Boone County    MO    15.0   both  \n",
       "457          WV      Berkeley County    WV    27.0   both  \n",
       "1378         OH         Clark County    OH    36.0   both  \n",
       "5804         WV        Putnam County    WV    12.0   both  \n",
       "7182         NY        Ulster County    NY    12.0   both  \n",
       "2058         NE       Douglas County    NE    48.0   both  \n",
       "4713         NJ      Monmouth County    NJ    72.0   both  \n",
       "7116         GA         Troup County    GA    10.0   both  \n",
       "7778         WI     Winnebago County    WI    22.0   both  \n",
       "7172         AL    Tuscaloosa County    AL    21.0   both  \n",
       "224          LA     Ascension Parish    LA    11.0   both  \n",
       "6834         CA    Stanislaus County    CA    66.0   both  \n",
       "5626         MA      Plymouth County    MA    49.0   both  \n",
       "6063         NH    Rockingham County    NH    85.0   both  \n",
       "1785         OH         Darke County    OH    13.0   both  \n",
       "7832         WV       Wyoming County    WV    24.0   both  \n",
       "1593         CA  Contra Costa County    CA    74.0   both  \n",
       "2505         WY       Fremont County    WY    10.0   both  \n",
       "4717         WV    Monongalia County    WV    13.0   both  \n",
       "4411         HI          Maui County    HI    18.0   both  \n",
       "1048         GA       Carroll County    GA    13.0   both  "
      ]
     },
     "execution_count": 118,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# convert years to integers\n",
    "od_pop[\"Year\"] = od_pop[\"Year\"].astype(\"int\")\n",
    "od_pop.sample(25)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 119,
   "metadata": {},
   "outputs": [],
   "source": [
    "# drop unneeded columns\n",
    "\n",
    "od_pop = od_pop.drop(columns=[\"County_y\", \"State\", \"_merge\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>FIPS</th>\n",
       "      <th>State Abbr</th>\n",
       "      <th>State</th>\n",
       "      <th>County</th>\n",
       "      <th>Year</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>Population</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>62</th>\n",
       "      <td>37001</td>\n",
       "      <td>NC</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Alamance County</td>\n",
       "      <td>2006</td>\n",
       "      <td>10.0</td>\n",
       "      <td>141462.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>930</th>\n",
       "      <td>37027</td>\n",
       "      <td>NC</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Caldwell County</td>\n",
       "      <td>2015</td>\n",
       "      <td>27.0</td>\n",
       "      <td>81518.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1689</th>\n",
       "      <td>23005</td>\n",
       "      <td>ME</td>\n",
       "      <td>Maine</td>\n",
       "      <td>Cumberland County</td>\n",
       "      <td>2007</td>\n",
       "      <td>31.0</td>\n",
       "      <td>278781.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2339</th>\n",
       "      <td>21067</td>\n",
       "      <td>KY</td>\n",
       "      <td>Kentucky</td>\n",
       "      <td>Fayette County</td>\n",
       "      <td>2011</td>\n",
       "      <td>41.0</td>\n",
       "      <td>301696.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6145</th>\n",
       "      <td>6067</td>\n",
       "      <td>CA</td>\n",
       "      <td>California</td>\n",
       "      <td>Sacramento County</td>\n",
       "      <td>2011</td>\n",
       "      <td>232.0</td>\n",
       "      <td>1433730.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5888</th>\n",
       "      <td>20155</td>\n",
       "      <td>KS</td>\n",
       "      <td>Kansas</td>\n",
       "      <td>Reno County</td>\n",
       "      <td>2014</td>\n",
       "      <td>10.0</td>\n",
       "      <td>63701.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5361</th>\n",
       "      <td>26139</td>\n",
       "      <td>MI</td>\n",
       "      <td>Michigan</td>\n",
       "      <td>Ottawa County</td>\n",
       "      <td>2008</td>\n",
       "      <td>10.0</td>\n",
       "      <td>261906.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>774</th>\n",
       "      <td>42017</td>\n",
       "      <td>PA</td>\n",
       "      <td>Pennsylvania</td>\n",
       "      <td>Bucks County</td>\n",
       "      <td>2012</td>\n",
       "      <td>125.0</td>\n",
       "      <td>625346.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5288</th>\n",
       "      <td>12095</td>\n",
       "      <td>FL</td>\n",
       "      <td>Florida</td>\n",
       "      <td>Orange County</td>\n",
       "      <td>2010</td>\n",
       "      <td>149.0</td>\n",
       "      <td>1148564.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4171</th>\n",
       "      <td>39095</td>\n",
       "      <td>OH</td>\n",
       "      <td>Ohio</td>\n",
       "      <td>Lucas County</td>\n",
       "      <td>2007</td>\n",
       "      <td>84.0</td>\n",
       "      <td>445482.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1361</th>\n",
       "      <td>32003</td>\n",
       "      <td>NV</td>\n",
       "      <td>Nevada</td>\n",
       "      <td>Clark County</td>\n",
       "      <td>2008</td>\n",
       "      <td>359.0</td>\n",
       "      <td>1912349.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3196</th>\n",
       "      <td>6023</td>\n",
       "      <td>CA</td>\n",
       "      <td>California</td>\n",
       "      <td>Humboldt County</td>\n",
       "      <td>2014</td>\n",
       "      <td>34.0</td>\n",
       "      <td>134494.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>166</th>\n",
       "      <td>23001</td>\n",
       "      <td>ME</td>\n",
       "      <td>Maine</td>\n",
       "      <td>Androscoggin County</td>\n",
       "      <td>2011</td>\n",
       "      <td>12.0</td>\n",
       "      <td>107439.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4076</th>\n",
       "      <td>9005</td>\n",
       "      <td>CT</td>\n",
       "      <td>Connecticut</td>\n",
       "      <td>Litchfield County</td>\n",
       "      <td>2003</td>\n",
       "      <td>12.0</td>\n",
       "      <td>187424.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7499</th>\n",
       "      <td>32031</td>\n",
       "      <td>NV</td>\n",
       "      <td>Nevada</td>\n",
       "      <td>Washoe County</td>\n",
       "      <td>2008</td>\n",
       "      <td>89.0</td>\n",
       "      <td>414793.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1015</th>\n",
       "      <td>40017</td>\n",
       "      <td>OK</td>\n",
       "      <td>Oklahoma</td>\n",
       "      <td>Canadian County</td>\n",
       "      <td>2011</td>\n",
       "      <td>17.0</td>\n",
       "      <td>119397.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3143</th>\n",
       "      <td>1069</td>\n",
       "      <td>AL</td>\n",
       "      <td>Alabama</td>\n",
       "      <td>Houston County</td>\n",
       "      <td>2011</td>\n",
       "      <td>12.0</td>\n",
       "      <td>102488.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4304</th>\n",
       "      <td>26101</td>\n",
       "      <td>MI</td>\n",
       "      <td>Michigan</td>\n",
       "      <td>Manistee County</td>\n",
       "      <td>2011</td>\n",
       "      <td>10.0</td>\n",
       "      <td>24774.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3600</th>\n",
       "      <td>44003</td>\n",
       "      <td>RI</td>\n",
       "      <td>Rhode Island</td>\n",
       "      <td>Kent County</td>\n",
       "      <td>2007</td>\n",
       "      <td>14.0</td>\n",
       "      <td>167515.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>720</th>\n",
       "      <td>12011</td>\n",
       "      <td>FL</td>\n",
       "      <td>Florida</td>\n",
       "      <td>Broward County</td>\n",
       "      <td>2009</td>\n",
       "      <td>305.0</td>\n",
       "      <td>1733310.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>879</th>\n",
       "      <td>37025</td>\n",
       "      <td>NC</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Cabarrus County</td>\n",
       "      <td>2015</td>\n",
       "      <td>23.0</td>\n",
       "      <td>196396.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5502</th>\n",
       "      <td>42101</td>\n",
       "      <td>PA</td>\n",
       "      <td>Pennsylvania</td>\n",
       "      <td>Philadelphia County</td>\n",
       "      <td>2014</td>\n",
       "      <td>523.0</td>\n",
       "      <td>1565460.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1804</th>\n",
       "      <td>37057</td>\n",
       "      <td>NC</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Davidson County</td>\n",
       "      <td>2007</td>\n",
       "      <td>19.0</td>\n",
       "      <td>159126.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2911</th>\n",
       "      <td>48201</td>\n",
       "      <td>TX</td>\n",
       "      <td>Texas</td>\n",
       "      <td>Harris County</td>\n",
       "      <td>2013</td>\n",
       "      <td>441.0</td>\n",
       "      <td>4353187.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2616</th>\n",
       "      <td>40051</td>\n",
       "      <td>OK</td>\n",
       "      <td>Oklahoma</td>\n",
       "      <td>Grady County</td>\n",
       "      <td>2012</td>\n",
       "      <td>18.0</td>\n",
       "      <td>53026.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       FIPS State Abbr           State               County  Year  Deaths  \\\n",
       "62    37001         NC  North Carolina      Alamance County  2006    10.0   \n",
       "930   37027         NC  North Carolina      Caldwell County  2015    27.0   \n",
       "1689  23005         ME           Maine    Cumberland County  2007    31.0   \n",
       "2339  21067         KY        Kentucky       Fayette County  2011    41.0   \n",
       "6145   6067         CA      California    Sacramento County  2011   232.0   \n",
       "5888  20155         KS          Kansas          Reno County  2014    10.0   \n",
       "5361  26139         MI        Michigan        Ottawa County  2008    10.0   \n",
       "774   42017         PA    Pennsylvania         Bucks County  2012   125.0   \n",
       "5288  12095         FL         Florida        Orange County  2010   149.0   \n",
       "4171  39095         OH            Ohio         Lucas County  2007    84.0   \n",
       "1361  32003         NV          Nevada         Clark County  2008   359.0   \n",
       "3196   6023         CA      California      Humboldt County  2014    34.0   \n",
       "166   23001         ME           Maine  Androscoggin County  2011    12.0   \n",
       "4076   9005         CT     Connecticut    Litchfield County  2003    12.0   \n",
       "7499  32031         NV          Nevada        Washoe County  2008    89.0   \n",
       "1015  40017         OK        Oklahoma      Canadian County  2011    17.0   \n",
       "3143   1069         AL         Alabama       Houston County  2011    12.0   \n",
       "4304  26101         MI        Michigan      Manistee County  2011    10.0   \n",
       "3600  44003         RI    Rhode Island          Kent County  2007    14.0   \n",
       "720   12011         FL         Florida       Broward County  2009   305.0   \n",
       "879   37025         NC  North Carolina      Cabarrus County  2015    23.0   \n",
       "5502  42101         PA    Pennsylvania  Philadelphia County  2014   523.0   \n",
       "1804  37057         NC  North Carolina      Davidson County  2007    19.0   \n",
       "2911  48201         TX           Texas        Harris County  2013   441.0   \n",
       "2616  40051         OK        Oklahoma         Grady County  2012    18.0   \n",
       "\n",
       "      Population  \n",
       "62      141462.0  \n",
       "930      81518.0  \n",
       "1689    278781.0  \n",
       "2339    301696.0  \n",
       "6145   1433730.0  \n",
       "5888     63701.0  \n",
       "5361    261906.0  \n",
       "774     625346.0  \n",
       "5288   1148564.0  \n",
       "4171    445482.0  \n",
       "1361   1912349.0  \n",
       "3196    134494.0  \n",
       "166     107439.0  \n",
       "4076    187424.0  \n",
       "7499    414793.0  \n",
       "1015    119397.0  \n",
       "3143    102488.0  \n",
       "4304     24774.0  \n",
       "3600    167515.0  \n",
       "720    1733310.0  \n",
       "879     196396.0  \n",
       "5502   1565460.0  \n",
       "1804    159126.0  \n",
       "2911   4353187.0  \n",
       "2616     53026.0  "
      ]
     },
     "execution_count": 120,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# rename columns for easier understanding\n",
    "od_pop = od_pop.rename(\n",
    "    columns={\"State Name\": \"State\", \"County_x\": \"County\"},\n",
    "    errors=\"raise\",\n",
    ")\n",
    "\n",
    "# reorder columns\n",
    "od_pop = od_pop[\n",
    "    [\"FIPS\", \"State Abbr\", \"State\", \"County\", \"Year\", \"Deaths\", \"Population\"]\n",
    "]\n",
    "\n",
    "# sort by state, county\n",
    "od_pop = od_pop.sort_values([\"State\", \"County\", \"Year\"])\n",
    "od_pop.sample(25)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>FIPS</th>\n",
       "      <th>State Abbr</th>\n",
       "      <th>State</th>\n",
       "      <th>County</th>\n",
       "      <th>Year</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>Population</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>373</th>\n",
       "      <td>51515</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2015</td>\n",
       "      <td>0.0</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1484</th>\n",
       "      <td>51560</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2015</td>\n",
       "      <td>0.0</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       FIPS State Abbr State County  Year  Deaths  Population\n",
       "373   51515        NaN   NaN    NaN  2015     0.0         NaN\n",
       "1484  51560        NaN   NaN    NaN  2015     0.0         NaN"
      ]
     },
     "execution_count": 121,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# check for null values\n",
    "od_pop[od_pop[\"State\"].isnull()]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 125,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>FIPS</th>\n",
       "      <th>State Abbr</th>\n",
       "      <th>State</th>\n",
       "      <th>County</th>\n",
       "      <th>Year</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>Population</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [FIPS, State Abbr, State, County, Year, Deaths, Population]\n",
       "Index: []"
      ]
     },
     "execution_count": 125,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# FIPS 51515 and 51560 represent two counties in Virginia, Bedford City and Clifton Forge Valley, that were incorporated in to other counties. It is safe to drop them\n",
    "\n",
    "od_pop = od_pop[(od_pop[\"FIPS\"] != 51515) & (od_pop[\"FIPS\"] != 51560)]\n",
    "od_pop[od_pop[\"State\"].isnull()]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create per capita deaths column\n",
    "od_pop[\"Deaths Per 100,000 People\"] = (od_pop[\"Deaths\"] / od_pop[\"Population\"]) * 100000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 128,
   "metadata": {},
   "outputs": [],
   "source": [
    "# save to excel\n",
    "\n",
    "od_pop.to_csv(\n",
    "    \"/Users/samsloate/Desktop/Data_Science/Opioids_Project/estimating-impact-of-opioids-2020-purlple-team/20_intermediate_files/death_data_with_pop.csv\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
